REATE USER IF NOT EXISTS "BANK" SALT '6476382fd4b9a5e7' HASH '774a656d2d7930dca1f0e892c16288c17365e059f6937bbe4402b64a0578986b' ADMIN;
CREATE SEQUENCE "PUBLIC"."HIBERNATE_SEQUENCE" START WITH 5;
CREATE SEQUENCE "PUBLIC"."ID_GENERATOR" START WITH 2;
CREATE CACHED TABLE "PUBLIC"."BANKACCOUNT"(
    "DTYPE" VARCHAR(31) NOT NULL,
    "ID" BIGINT NOT NULL,
    "ACCOUNT_NUMBER" VARCHAR(255) NOT NULL,
    "CURRENT_BALANCE" DOUBLE,
    "INTEREST_RATE" DOUBLE,
    "MINIMUM_BALANCE" DOUBLE,
    "ACCOUNT_TYPE" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."BANKACCOUNT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.BANKACCOUNT;
INSERT INTO "PUBLIC"."BANKACCOUNT" VALUES
('SavingAccount', 1, '101', 23000.0, 4.5, 10000.0, 'Saving'),
('CurrentAccount', 3, '1', 23000.0, 0.0, 20000.0, 'Current');
CREATE CACHED TABLE "PUBLIC"."BANKACCOUNT_TRANSACTIONS"(
    "BANK_ACCOUNT_ID" BIGINT NOT NULL,
    "TRANSACTIONS_ID" BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BANKACCOUNT_TRANSACTIONS;
CREATE CACHED TABLE "PUBLIC"."BRANCH"(
    "ID" BIGINT NOT NULL,
    "BRANCH_ID" VARCHAR(255) NOT NULL
);
ALTER TABLE "PUBLIC"."BRANCH" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.BRANCH;
INSERT INTO "PUBLIC"."BRANCH" VALUES
(1, '1');
CREATE CACHED TABLE "PUBLIC"."BRANCH_BANK_ACCOUNTS"(
    "BRANCH_ID" BIGINT NOT NULL,
    "BANK_ACCOUNTS_ID" BIGINT NOT NULL
);
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.BRANCH_BANK_ACCOUNTS;
INSERT INTO "PUBLIC"."BRANCH_BANK_ACCOUNTS" VALUES
(1, 1),
(1, 3);
CREATE CACHED TABLE "PUBLIC"."BRANCH_CUSTOMERS"(
    "BRANCH_ID" BIGINT NOT NULL,
    "CUSTOMERS_ID" BIGINT NOT NULL
);
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.BRANCH_CUSTOMERS;
INSERT INTO "PUBLIC"."BRANCH_CUSTOMERS" VALUES
(1, 2),
(1, 4);
CREATE CACHED TABLE "PUBLIC"."CUSTOMER"(
    "ID" BIGINT NOT NULL,
    "PAN_NUMBER" VARCHAR(255) NOT NULL
);
ALTER TABLE "PUBLIC"."CUSTOMER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("ID");
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.CUSTOMER;
INSERT INTO "PUBLIC"."CUSTOMER" VALUES
(2, 'AB12'),
(4, 'AB123');
CREATE CACHED TABLE "PUBLIC"."CUSTOMER_BANK_ACCOUNTS"(
    "CUSTOMER_ID" BIGINT NOT NULL,
    "BANK_ACCOUNTS_ID" BIGINT NOT NULL
);
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.CUSTOMER_BANK_ACCOUNTS;
INSERT INTO "PUBLIC"."CUSTOMER_BANK_ACCOUNTS" VALUES
(2, 1),
(4, 3);
CREATE CACHED TABLE "PUBLIC"."TRANSACTION"(
    "ID" BIGINT NOT NULL,
    "AMOUNT" DOUBLE,
    "TRANSACTION_ID" VARCHAR(255) NOT NULL,
    "TYPE" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."TRANSACTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TRANSACTION;
ALTER TABLE "PUBLIC"."BANKACCOUNT_TRANSACTIONS" ADD CONSTRAINT "PUBLIC"."UK_8WDBNX0YOBF4GPMO4PQGB3I9W" UNIQUE("TRANSACTIONS_ID");
ALTER TABLE "PUBLIC"."TRANSACTION" ADD CONSTRAINT "PUBLIC"."UK_NEVCWMPU8HB3A1NAPH2FYVQYU" UNIQUE("TRANSACTION_ID");
ALTER TABLE "PUBLIC"."BRANCH_BANK_ACCOUNTS" ADD CONSTRAINT "PUBLIC"."UK_FQYB2YLYSSFKATST87Y8U6E5T" UNIQUE("BANK_ACCOUNTS_ID");
ALTER TABLE "PUBLIC"."BRANCH_CUSTOMERS" ADD CONSTRAINT "PUBLIC"."UK_G66GB0FIDABYGLL2LAPP5FNUJ" UNIQUE("CUSTOMERS_ID");
ALTER TABLE "PUBLIC"."CUSTOMER" ADD CONSTRAINT "PUBLIC"."UK_44P4IJ10R4N9FT1FIMYN5EVFM" UNIQUE("PAN_NUMBER");
ALTER TABLE "PUBLIC"."BANKACCOUNT" ADD CONSTRAINT "PUBLIC"."UK_JH68LRLR5QK5XG5TVJ5YN67CI" UNIQUE("ACCOUNT_NUMBER");
ALTER TABLE "PUBLIC"."BRANCH" ADD CONSTRAINT "PUBLIC"."UK_9302VTB3V1EL71LES6UT8SVC0" UNIQUE("BRANCH_ID");
ALTER TABLE "PUBLIC"."CUSTOMER_BANK_ACCOUNTS" ADD CONSTRAINT "PUBLIC"."UK_HDPY2OGGCB1TUWMDUSSU8O8QX" UNIQUE("BANK_ACCOUNTS_ID");
ALTER TABLE "PUBLIC"."CUSTOMER_BANK_ACCOUNTS" ADD CONSTRAINT "PUBLIC"."FKPX3UQIJUO0C0DYMTPMPRLRFNQ" FOREIGN KEY("CUSTOMER_ID") REFERENCES "PUBLIC"."CUSTOMER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."CUSTOMER_BANK_ACCOUNTS" ADD CONSTRAINT "PUBLIC"."FKBTG81FJJA01LXLB73OMP0TU5U" FOREIGN KEY("BANK_ACCOUNTS_ID") REFERENCES "PUBLIC"."BANKACCOUNT"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."BRANCH_BANK_ACCOUNTS" ADD CONSTRAINT "PUBLIC"."FKC3DJX61KMD60LBQC34ROK41V2" FOREIGN KEY("BANK_ACCOUNTS_ID") REFERENCES "PUBLIC"."BANKACCOUNT"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."BRANCH_CUSTOMERS" ADD CONSTRAINT "PUBLIC"."FKD7ASR2V09B2HNGPPCURWBI2H1" FOREIGN KEY("BRANCH_ID") REFERENCES "PUBLIC"."BRANCH"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."BANKACCOUNT_TRANSACTIONS" ADD CONSTRAINT "PUBLIC"."FKL7CCWGMIRQT8HQ58757ITXN3" FOREIGN KEY("BANK_ACCOUNT_ID") REFERENCES "PUBLIC"."BANKACCOUNT"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."BRANCH_BANK_ACCOUNTS" ADD CONSTRAINT "PUBLIC"."FKFY4YQQPWHA8V1GUDO5WPN1DE6" FOREIGN KEY("BRANCH_ID") REFERENCES "PUBLIC"."BRANCH"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."BANKACCOUNT_TRANSACTIONS" ADD CONSTRAINT "PUBLIC"."FK80K02STOPSXSSL4HJYJRODHYH" FOREIGN KEY("TRANSACTIONS_ID") REFERENCES "PUBLIC"."TRANSACTION"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."BRANCH_CUSTOMERS" ADD CONSTRAINT "PUBLIC"."FK6ULMJOLOPLQCQPJQAUTQT2KMG" FOREIGN KEY("CUSTOMERS_ID") REFERENCES "PUBLIC"."CUSTOMER"("ID") NOCHECK;